### ISSUE TITLE
Error/crash during rename attempt?

### ISSUE THREAD

**Issue by Beetlecat** [Icecovery/Game-Data-Switcher#1]
![capture](https://user-images.githubusercontent.com/2371787/36696717-d7768d9e-1af9-11e8-863f-11fef7bcdf9f.JPG)

"Could not find part of the path" when attempting to rename an existing, not-currently-active gamedata folder. Is it missing a slash in the highlighted area (on my attachment)?

Thanks! :D

**Comment by linuxgurugamer** [comment]
I just submitted a PR fixing several issues that I found.
You can get my version from here: https://github.com/linuxgurugamer/Game-Data-Switcher/releases/tag/1.0.3-beta

**Comment by Icecovery** [comment]
Released V1.0.5, this issues has been fixed.
Thanks to linuxgurugamer.

**Comment by Icecovery** [comment]
Released V1.0.5, this issues has been fixed.
Thanks to linuxgurugamer.
